FROM node:18-slim-bullseye

WORKDIR /app

ENTRYPOINT ["node"]

# (Optional, but good practice for security) Create a non-root user
# RUN adduser --disabled-password --gecos "" --shell /bin/sh appuser
# USER appuser