FROM ruby:3.1-slim-bullseye

WORKDIR /app

ENTRYPOINT ["ruby"]

# (Optional, but good practice for security) Create a non-root user
# RUN adduser --disabled-password --gecos "" --shell /bin/sh appuser
# USER appuser